# Site settings
title: "Oruma's Data Analytics Portfolio"
description: "Showcasing my analytics projects, dashboards, and Power BI work"
theme: jekyll-theme-cayman

# Optional social links
author:
  name: Oruma Shuaibu Ojochenemi
  email: orumashuaib@gmail.com
  github: orumaa

# Navigation (if you add more pages later)
header_pages:
  - index.md
  - projects.md
  - about.md

# Minima theme settings
Cayman :
  social_links:
    github: https://github.com/orumaa
    LinkedIn: https://www.linkedin.com/in/shuaibu-oruma-529192138/

